kind: Deployment
apiVersion: apps/v1
metadata:
  name:  my-react-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatsby-admin-template
  template:
    metadata:
      labels:
        app: gatsby-admin-template
    spec:
      containers:
        - name: gatsby-admin-template
          image: localhost:5000/gatsby-admin-template:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: gatsby-admin-template
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32000
  selector:
    app: gatsby-admin-template